package Kontohantering;

import java.util.ArrayList;

public class Customer {
	//Customer class only contains name, personnumber and list of associated accounts
	//Setters and getters autogenerated since I wanted to try that, very convenient. Im keeping the this.syntax to see how i like it
	private String cName;
	private long personNumber;
	//According to book arraylist is preferble to arraylist when size changes
	ArrayList<Integer> accounts = new ArrayList<Integer>();
	
	//AHA! constructors are also autogenerated. Every customer must have a name and Personnumber but not necesarily an account.
	public Customer(String cName, long personNumber) {
	//There has to be a personnumber, in reality there is probably a very good open source function to confirm that a personnumber is really Swedish personnumber
		if (personNumber > 0){
		this.cName = cName;
		this.personNumber = personNumber;
		}else{
			System.out.print("You need to provide a name and a person number");
		}
	}
	//autogenerated setMethod edited to only add one account at a time. 
	public void addAccount(int newAccount) {
		accounts.add(newAccount);
	}
	public void removeAccounts(int accountNum){
		accounts.remove(accountNum);
	}
	public ArrayList<Integer> getAccounts() {
		return accounts;
	}
	//Autogenerated
	public String getcName() {
		return cName;
	}
	public void setcName(String cName) {
		this.cName = cName;
	}
	public long getPersonNumber() {
		return personNumber;
	}
	//Personnumbers DO change at times. Usage should be carefully monitored tough.
	public void setPersonNumber(long personNumber) {
		this.personNumber = personNumber;
	}
	public String toString(){
		StringBuilder stringbuilder = new StringBuilder();
		stringbuilder.append(getcName());
		stringbuilder.append(getPersonNumber());
		stringbuilder.append(getAccounts());
		String presentation = stringbuilder.toString();
		
		return presentation;

	}
}